use `bjm`;

-- -----------------------------------------------------
-- Table `bjm`.`LOK_SABHA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjm`.`LOK_SABHA` ;

CREATE TABLE IF NOT EXISTS `bjm`.`LOK_SABHA` (
  `CONSTITUENCY` VARCHAR(100) NOT NULL,
  `STATE_CODE` CHAR(2) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE INDEX `BY_CODE` ON `bjm`.`LOK_SABHA` (`STATE_CODE` ASC) VISIBLE;

ALTER TABLE `bjm`.`USER`
    ADD 
    CONSTRAINT `fk_USER_LOK_SABHA1`
    FOREIGN KEY (`LOK_SABHA_ID`)
    REFERENCES `bjm`.`LOK_SABHA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;
    
CREATE INDEX `fk_USER_LOK_SABHA1_idx` ON `bjm`.`USER` (`LOK_SABHA_ID` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `bjm`.`VIDHAN_SABHA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjm`.`VIDHAN_SABHA` ;

CREATE TABLE IF NOT EXISTS `bjm`.`VIDHAN_SABHA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STATE_CODE` CHAR(2) NOT NULL,
  `CONSTITUENCY` VARCHAR(100) NOT NULL,
  `LOK_SABHA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_VIDHAN_SABHA_LOK_SABHA1`
    FOREIGN KEY (`LOK_SABHA_ID`)
    REFERENCES `bjm`.`LOK_SABHA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ON_STATE_CODE` ON `bjm`.`VIDHAN_SABHA` (`STATE_CODE` ASC) VISIBLE;

CREATE INDEX `fk_VIDHAN_SABHA_LOK_SABHA1_idx` ON `bjm`.`VIDHAN_SABHA` (`LOK_SABHA_ID` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `bjm`.`VS_CANDIDATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjm`.`VS_CANDIDATE` ;

CREATE TABLE IF NOT EXISTS `bjm`.`VS_CANDIDATE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `VIDHAN_SABHA_ID` INT NOT NULL,
  `REPRESENT` TINYINT(1) NOT NULL DEFAULT 0,
  `NAME_CONF_COUNT` INT(3) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_VS_CANDIDATE_VIDHAN_SABHA1`
    FOREIGN KEY (`VIDHAN_SABHA_ID`)
    REFERENCES `bjm`.`VIDHAN_SABHA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VS_CANDIDATE_VIDHAN_SABHA1_idx` ON `bjm`.`VS_CANDIDATE` (`VIDHAN_SABHA_ID` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `bjm`.`LS_CANDIDATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bjm`.`LS_CANDIDATE` ;

CREATE TABLE IF NOT EXISTS `bjm`.`LS_CANDIDATE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `LOK_SABHA_ID` INT NOT NULL,
  `REPRESENT` TINYINT(1) NOT NULL DEFAULT 0,
  `NAME_CONF_COUNT` INT(3) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_LS_CANDIDATE_LOK_SABHA1`
    FOREIGN KEY (`LOK_SABHA_ID`)
    REFERENCES `bjm`.`LOK_SABHA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_LS_CANDIDATE_LOK_SABHA1_idx` ON `bjm`.`LS_CANDIDATE` (`LOK_SABHA_ID` ASC) VISIBLE;
